added basic application layout and displayed the map and fixed git ig…
stein4444/TravelManager pull request #1
Opened 2021-11-04 15:30 UTC by stein4444

2021-11-04 16:19 UTC, pastukh0v commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +    public class MapViewModel : INotifyPropertyChanged
You already have the `ViewModelBase` class implementing `INotifyPropertyChanged` so could just inherit that class.

2021-11-04 16:26 UTC, pastukh0v requested changes

2021-11-04 16:26 UTC, pastukh0v commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +            set { _map = value; OnPropertyChanged(); }
Could use `SetProperty()` of `ViewModelBase`

2021-11-04 16:26 UTC, pastukh0v commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +        protected void OnPropertyChanged([CallerMemberName] string propertyName = null) =>
`ViewModelBase` has the same code which can be reused

2021-11-04 16:26 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml
> +    <Window.Resources>
IT would be nice to use `DataContext` to set `MapViewModel` as a viewmodel for this view

2021-11-04 16:26 UTC, pastukh0v commented on TravelManager.Presentation/App.xaml.cs
> +                // Initialize the ArcGIS Runtime before any components are created.
These comments do not add any essential info so can be removed

2021-11-05 08:58 UTC, stein4444 commented on TravelManager.Presentation/App.xaml.cs
> +                // Initialize the ArcGIS Runtime before any components are created.
ok I'll remove

2021-11-05 09:01 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +        protected void OnPropertyChanged([CallerMemberName] string propertyName = null) =>
sure

2021-11-05 09:03 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +    public class MapViewModel : INotifyPropertyChanged
makes sense, I didn't pay attention to it

2021-11-05 12:45 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MapViewModel.cs
> +            set { _map = value; OnPropertyChanged(); }
Fixed

2021-11-05 13:01 UTC, stein4444 commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml
> +    <Window.Resources>
fixed

2021-11-05 13:08 UTC, pastukh0v approved these changes

2021-11-05 13:09 UTC, merged