added bindings to main window and implemented MahApp Metro style to p…
stein4444/TravelManager pull request #2
Opened 2021-11-08 12:27 UTC by stein4444

…roject

2021-11-08 18:31 UTC, pastukh0v requested changes

2021-11-08 18:31 UTC, pastukh0v commented on TravelManager.Presentation/App.xaml
> +                <mainView:MainWindow/>
Do we really need this if we set a `DataContext` for `MainWindow` in `MainWindow.xaml`?

2021-11-08 18:31 UTC, pastukh0v commented on TravelManager.Presentation/ViewModels/MainWindowViewModel.cs
> +    class MainWindowViewModel : ViewModelBase
Let's have a convention that we need to specify access modifiers explicitly, so `public class MainWindowViewModel` in this case. Please check the other files as well

2021-11-08 19:29 UTC, stein4444 commented on TravelManager.Presentation/App.xaml
> +                <mainView:MainWindow/>
no we needed

2021-11-08 19:35 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MainWindowViewModel.cs
> +        public MapViewModel MapVm { get; set; }
Sure, It would be more correct

2021-11-08 19:39 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MainWindowViewModel.cs
> +        #region PrivateFields
sure

2021-11-08 19:48 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MainWindowViewModel.cs
> +    class MainWindowViewModel : ViewModelBase
did not pay attention on it, I'll fix it in new commit

2021-11-09 08:02 UTC, stein4444 commented on TravelManager.Presentation/ViewModels/MainWindowViewModel.cs
> +        /// Gets or sets the map
missed it

2021-11-09 08:03 UTC, stein4444 commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml
> +        Title="{Binding Title}" Height="600" Width="800" Background="#4889f0">
sure it'll be great

2021-11-09 09:52 UTC, pastukh0v approved these changes

2021-11-09 10:03 UTC, merged