added functionality for drawing poi on the map
stein4444/TravelManager pull request #3
Opened 2021-11-15 14:05 UTC by stein4444

2021-11-15 14:34 UTC, pastukh0v requested changes

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/ViewModels/MenuViewModel.cs
> +                new Poi { ImagePath = "/Images/beach.png", Name = "Beach"},
Can we just create this list once and return it every time it's requested?

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml
> +                    <esri:MapView x:Name="MyMap" Map="{Binding MapViewModel.Map}" />
`MyMap` isn't a very descriptive name. Something like `MainMap` would probably fit more

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                if (pathToIcon.ImagePath == null)
Let's add `{}` for all blocks of code, even if a block contains just one line of code, this improves readability

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                var pathToIcon = PoiTypesListBox.SelectedItem as Poi;
In this case we are sure that the listbox contains instances of the `Poi` class, so it is preferable to use direct cast in such cases,  e.g. `var pathToIcon = (Poi)PoiTypesListBox.SelectedItem ;`

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                    MessageBox.Show($"{pathToIcon}");
Is it really possible that `ImagePath` can be `null` here?

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                await CreatePictureMarkerSymbolFromResources(pathToIcon.ImagePath, pathToIcon.Name);
The method accepts two arguments read from the same variable. Can just pass in `pathToIcon` and read all needed properties from it in `CreatePictureMarkerSymbolFromResources()`

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +            Geometry mapPoint = await MyMap.SketchEditor.StartAsync(SketchCreationMode.Point, false);
`mapPoint` is going to be `null` if the user cancels drawing by hitting the `Esc` key and a `NullReferenceException` will be thrown at line `59`.

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                name, Color.Black, 15, Esri.ArcGISRuntime.Symbology.HorizontalAlignment.Center,
Let's make it so that the user can enter the name in a textbox so that we can have different names for different types of Poi

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +            Uri fileUri = new Uri($"pack://application:,,,{path}");
Can we add a `readonly` property of `Uri` type to the `Poi` class so that we don't have to construct it here?

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                name, Color.Black, 15, Esri.ArcGISRuntime.Symbology.HorizontalAlignment.Center,
Use `using` statements to avoid long type names

2021-11-15 14:34 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +            try
I suggest that we refactor this to be implemented in more `MVVM`-friendly way. The logic in this click handler can be extracted into a new command in the view model.

2021-11-16 14:17 UTC, pastukh0v requested changes

2021-11-16 14:17 UTC, pastukh0v commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                var slectedPoi = (Poi)PoiTypesListBox.SelectedItem;
`selected`

2021-11-16 14:28 UTC, stein4444 commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +                var slectedPoi = (Poi)PoiTypesListBox.SelectedItem;
fixed

2021-11-16 14:29 UTC, stein4444 commented on TravelManager.Presentation/Views/Windows/MainWindow.xaml.cs
> +            try
will be fixed

2021-11-16 14:29 UTC, merged